paths:
    jquery: "lib/jquery"
    underscore: "lib/underscore"
    backbone: "lib/backbone"
    text: "lib/text"
    bootstrap: "lib/bootstrap.min"

shim:
    backbone:
        deps: [underscore, jquery]
        exports: Backbone
    underscore:
        exports: _
    text:
        deps: [backbone, underscore]
    bootstrap:
        deps: [jquery]

